# Generated by Django 4.0.1 on 2022-01-21 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='qoshilgan fani')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('phone_num', models.CharField(max_length=9, verbose_name='Telefon raqami')),
                ('level', models.CharField(max_length=100, verbose_name='Ilmiy darajasi darajasi')),
                ('sertificate', models.FileField(blank=True, null=True, upload_to='sertificetes/<django.db.models.fields.CharField>/', verbose_name='Sertificate')),
                ('experience', models.CharField(max_length=50, verbose_name='Tajribasi')),
                ('registred_time', models.DateTimeField(auto_now_add=True, verbose_name='royhatga olingan vaqt')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name="O'qitadigan fani")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('phone_num', models.CharField(max_length=9, verbose_name='Telefon raqami')),
                ('study_days', models.CharField(choices=[('du-ch-j', 'Du-Ch-J'), ('se-p-sh', 'Se-P-Sh'), ('du-se-ch-p-j', 'Du-Se-Ch-P-J'), ('har kunlik', 'Har Kunlik'), ('option', 'Option')], default='option', max_length=50, verbose_name="O'qish Kunlari")),
                ('study_type', models.CharField(choices=[('team', 'Team'), ('induvidual', 'Induvidual'), ('option', 'Option')], default='option', max_length=50, verbose_name="O'qish turi")),
                ('lesson_time', models.CharField(max_length=50, verbose_name='Dars boshlanish vaqti')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yhatga olingan vaqti")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name="O'rganadigan fani")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name="O'qituvchisi")),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(default=0, verbose_name='Tolov summasi')),
                ('payed_date', models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqt")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Talaba')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='Qaysi fan uchun')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name="O'qituvchisi")),
            ],
        ),
        migrations.CreateModel(
            name='Harajatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nima uchun')),
                ('amount', models.IntegerField(default=0, verbose_name='Qancha miqdorda')),
                ('used_date', models.DateTimeField(auto_now_add=True, verbose_name='Ishlatilgan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
