# Generated by Django 4.0.1 on 2022-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.CharField(max_length=100, verbose_name='Ilmiy darajasi'),
        ),
    ]
