# Generated by Django 4.0.1 on 2022-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_payment_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harajatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nima uchun')),
                ('amount', models.IntegerField(verbose_name='Qancha miqdorda')),
                ('used_date', models.DateTimeField(auto_now_add=True, verbose_name='Ishlatilgan vaqti')),
            ],
        ),
    ]
