# Generated by Django 4.0.2 on 2022-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teacher_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sertificate',
            field=models.ImageField(blank=True, null=True, upload_to='sertificetes/teachers/', verbose_name='Sertificate'),
        ),
    ]
