# Generated by Django 4.0.1 on 2022-01-10 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='MANZIL'),
            preserve_default=False,
        ),
    ]
