# Generated by Django 4.0.2 on 2022-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='default_img/default.png', null=True, upload_to='user_pic/', verbose_name='Profile uchun Rasm'),
        ),
    ]
