# Generated by Django 4.0.1 on 2022-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_pic/', verbose_name='Profile uchun Rasm'),
        ),
    ]
